---
ID: "84cb9c2c-e4c7-4eaa-adcb-2cb02ee27d2d"
Parent: "ecee7850-93b3-479b-9f78-53c1ac892a46"
Template: "c3b037a0-46e5-4b67-ac7a-a144b962a56f"
Path: /sitecore/layout/Placeholder Settings/Project/SitecoreXMC/Services
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240624T124227Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\iFwou2ptGi
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\iFwou2ptGi
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "35323a24-cb03-4eb2-bef9-afd4b453be23"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iFwou2ptGi
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240624T124227Z
