---
ID: "b88cd811-3eee-4364-bad9-eeb83ef102a2"
Parent: "5667f9bd-5472-43ec-8bc9-27cc68eaf914"
Template: "5667f9bd-5472-43ec-8bc9-27cc68eaf914"
Path: /sitecore/templates/Project/SitecoreXMC/Services/Rendering Parameters/Services Teaser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c9ec9f59-1d02-4e55-992d-10017db90bd4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iFwou2ptGi
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240624T124607Z
