---
ID: "42b3d0f0-98f6-46c6-8317-7c421278aa95"
Parent: "a2eeb069-44b6-4a39-8a39-9c14d2864528"
Template: "a2eeb069-44b6-4a39-8a39-9c14d2864528"
Path: /sitecore/templates/Foundation/Master Data/Checkout Attributes Values/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240315T131711Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "65fe34e2-84bc-459f-a4ad-8dc019b3dc49"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240315T131711Z
