---
ID: "311fb639-969a-4988-add4-39a6fe728923"
Parent: "5288d54b-295e-5fed-9225-d9a08f763234"
Template: "ccd7acfa-6848-5b61-960c-fb0a533d3cd3"
Path: "/sitecore/content/sitecore-jss-app/home/product"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{8F536324-5EB0-4ED3-BF25-AA1A50EDF924}"
              p:after="*[1=2]"
              s:id="{4701A196-FE30-4FAB-A76D-3DD8282C9E0B}"
              s:ph="jss-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240331T112219Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{AF32C98B-C828-42AF-A649-74C1DE3303FB}"
    - ID: "50e0c6e5-f875-53c2-b98c-9b5b5a96705b"
      Hint: pageTitle
      Value: Product
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8b374ae9-ef9f-4f00-9e41-1ff8212923c9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240331T112430Z
