---
ID: "7733fa5c-4736-4da6-8476-a93df5bc52f7"
Parent: "df0933bb-7588-400c-adba-669d5c34f72c"
Template: "df0933bb-7588-400c-adba-669d5c34f72c"
Path: /sitecore/templates/Project/SitecoreXMC/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240606T092100Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jay@sourceved.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jay@sourceved.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f2bd6467-9409-421e-8e83-ea6c589e8c05"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jay@sourceved.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240606T092100Z
