---
ID: "6735ca87-85a6-434d-b45a-f418171741af"
Parent: "71fb8ab7-a0b8-4ccc-9bb3-e58971ed5910"
Template: "71fb8ab7-a0b8-4ccc-9bb3-e58971ed5910"
Path: /sitecore/templates/Feature/Footer/Footer Links/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F30C429E-01CB-4F69-B2F0-1CB3C5AB40BC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240521T120519Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "02fde605-f3a3-420a-bab7-fbf8b2b84a02"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240521T121222Z
    - ID: "f72b1b7f-eb56-4c99-bcaa-61ab5953a9ca"
      Hint: SectionHeader
      Value: $name
