---
ID: "f08c2bd1-851e-4419-a319-5fa3b941fac6"
Parent: "f30c429e-01cb-4f69-b2f0-1cb3c5ab40bc"
Template: "f30c429e-01cb-4f69-b2f0-1cb3c5ab40bc"
Path: /sitecore/templates/Feature/Footer/Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240521T120605Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1084544d-3626-4b49-9f25-0e28a4f9aee6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240521T120611Z
    - ID: "e9005b1e-a413-4f01-87eb-0ef1d1abc06e"
      Hint: Name
      Value: $name
