---
ID: "09967485-eb94-4d8d-9a1f-bf9de8686baf"
Parent: "84b4281c-4c1d-4836-8987-ecaba72bec96"
Template: "84b4281c-4c1d-4836-8987-ecaba72bec96"
Path: /sitecore/templates/Foundation/Master Data/Measures Dimensions/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240318T053931Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fec82c59-a0af-44c1-ace2-5e386d6f6395"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240318T055726Z
